### ISSUE TITLE
Current version of interproscan does not work on java version 1.8

### ISSUE THREAD

**Issue by dnieuw** [ebi-pf-team/interproscan-docs#1]
Dear interproscan team,

The minimal requirements have to be updated in the documentation since interproscan version 5.47-82.0 (which I just downloaded and installed) does not work with java version 1.8.0_152-release. The provided test example told me that java version 11 was required to run interproscan. I created a new conda environment containing java version 11 and in this environment the test in the docs worked.

Kind regards,

David Nieuwenhuijse

**Comment by gsn7** [comment]
hi, let me know which documentation you referenced as you can check here https://interproscan-docs.readthedocs.io/en/latest/InstallationRequirements.html, we have updated the java 11 requirement in the documentation since version 5.37-76.0 

i know there is another page https://interproscan5-docs.readthedocs.io/ that is not referenced anywhere and that has old documentation and we will take it down asap.
